### ISSUE TITLE
failed to unmarshal CurrencyAgg.z

### ISSUE THREAD

**Issue by lrondanini** [polygon-io/client-go#254] opened 2023-03-03 01:01 UTC
Hi all,

I have a websocket open to:

    Feed:   polygonws.RealTime, 
    Market: polygonws.Crypto,

Subscribing to: 
  
    client.Subscribe(polygonws.CryptoMinAggs)

Every so often I get this error:

failed to unmarshal message: json: cannot unmarshal number 8.652169e+06 into Go struct field CurrencyAgg.z of type int32

If I look into models.CurrencyAgg says that

    AVGTradeSize int32 `json:"z,omitempty"`

Let me know if you need more information

**Comment by justinpolygon** [comment] 2023-03-03 07:52
Hey @lrondanini, this is an interesting one because if I'm going my math right the decimal value 8.652169e+06 represents the number 8,652,169. In this case, the value can be represented as an int32 since 8,652,169 falls within the range of values that can easily be represented by this type.

So, I'm wondering if something else is going on here. Can you tell me a bit more about your operating system, the `go -version`, and what version of this `polygon-io/client-go` you're running? I'm not sure what would cause this. Would you mind adding some additional logging for json unmarshal error's? It would be great if we could capture the timeframe and a way to identify the aggregate that cause it so we can try and reproduce this.

**Comment by lrondanini** [comment] 2023-03-04 00:42
hey @justinpolygon,
Im on go version go1.20.1 darwin/amd64 and Im using the latest polygon-io/client-go (I installed it 2 days ago)
Ive seen this error only with crypto, everything works for stocks. This is the code Im running:

`package polygon

import (
	"os"
	"os/signal"

	polygonws "github.com/polygon-io/client-go/websocket"
	"github.com/polygon-io/client-go/websocket/models"
	"github.com/sirupsen/logrus"

	"stocks-prices-manager/utils"
)

type Polygon struct {
	client        *polygonws.Client
	log           *logrus.Logger
	tradesManager TradesManager
}

func (p *Polygon) Init() {
	var conf = utils.GetConfiguration()
	var log = utils.GetLogger()

	c, err := polygonws.New(polygonws.Config{
		APIKey: conf.POLYGON_CRYPTO_API_KEY, 
		Feed:   polygonws.RealTime,         
		Market: polygonws.Crypto,           
		Log:    log,
	})

	if err != nil {
		log.Fatal(err)
	}

	p.client = c
	p.log = log

	p.tradesManager = CreateTradeManager()
}

func (p *Polygon) CleanUp() {
	p.client.Close()
	p.tradesManager.Close()
}

func (p *Polygon) StartWebsocket() {
	defer p.CleanUp()

	_ = p.client.Subscribe(polygonws.CryptoMinAggs)

	if err := p.client.Connect(); err != nil {
		return
	}

	p.log.Info("POLYGON WEBSOCKET SUCCESSFULLY CONNECTED")

	sigint := make(chan os.Signal, 1)
	signal.Notify(sigint, os.Interrupt)

	for {
		select {
		case <-sigint:
			return
		case <-p.client.Error():
			return
		case out, more := <-p.client.Output():
			if !more {
				return
			}

                        fmt.Println(out)

			switch out.(type) {
			case models.CurrencyAgg:
				p.tradesManager.ProcessCryptoAggregate(out.(models.CurrencyAgg))				
			case models.EquityAgg:
				p.tradesManager.ProcessTradeAggregate(out.(models.EquityAgg))				
			}
		}
	}

}
`

this is an output with the error, that occurred at 2023-03-04T01:39 = 2023-03-04T00:39 UTC

`{{XA} LRC-USD 0.34 0.3407 0.341 0.34 14802.85839712 0.3409 1677890280000 1677890340000 1233}
{{XA} ETH-BTC 0.0703 0.07032 0.07032556 0.0703 1.56253203 0.07031 1677890280000 1677890340000 0}
{{XA} UST-USD 1.0002 1.0002 1.0002 1.0001 2222.59666756 1.0002 1677890280000 1677890340000 277}
{{XA} ETP-USD 0.025107 0.025107 0.025107 0.025107 1.13114838 0.02511 1677890280000 1677890340000 0}
{{XA} LCX-USD 0.1058 0.1055 0.1058 0.1055 8407.1 0.1056 1677890280000 1677890340000 2101}
{{XA} SWFTC-USD 0.001226 0.001224 0.001226 0.001224 40000 0.001225 1677890280000 1677890340000 20000}
{{XA} BADGER-USD 3.34 3.35 3.35 3.34 0.595 3.345 1677890280000 1677890340000 0}
{{XA} TRX-USD 0.067408 0.067408 0.067408 0.067408 84.09471968 0.06741 1677890280000 1677890340000 42}
{{XA} KNC-USD 0.76789 0.7702 0.7705 0.76789 1113.78946398 0.7705 1677890280000 1677890340000 278}
{{XA} API3-USD 1.506 1.506 1.506 1.506 50.2 1.506 1677890280000 1677890340000 50}
{{XA} ETH-USD 1570.62 1573.66 1574.15 1570.6 340.61371521 1572.8018 1677890280000 1677890340000 0}
{{XA} SAND-USD 0.6479 0.6525 0.6542 0.6479 39687.99585643 0.6489 1677890280000 1677890340000 901}
{{XA} REEF-USD 0.0029913 0.0029913 0.0029913 0.0029913 1577.34273936 0.002991 1677890280000 1677890340000 788}
{{XA} JASMY-USD 0.00556 0.00559 0.00559 0.00556 301875 0.005577 1677890280000 1677890340000 43125}
{{XA} BTC-EUR 21008 21037.57 21037.57 21008 0.37686038 21021.1117 1677890280000 1677890340000 0}
{{XA} MANA-USD 0.6049 0.6078 0.609 0.6049 20515.97024155 0.6073 1677890280000 1677890340000 330}
{{XA} TRU-USD 0.0955 0.0955 0.0955 0.0948 248069.3 0.09539 1677890280000 1677890340000 5278}
{{XA} GLM-USD 0.2495 0.2495 0.2495 0.2495 80 0.2495 1677890280000 1677890340000 80}
{{XA} CRPT-USD 0.1091 0.1091 0.1091 0.1091 52.8 0.1091 1677890280000 1677890340000 52}
{{XA} AAVE-USD 77.16 77.32 77.36 77.16 28.46514773 77.2562 1677890280000 1677890340000 2}
{{XA} DSH-USD 69.419 69.419 69.419 69.419 0.6 69.419 1677890280000 1677890340000 0}
{{XA} DOGE-USD 0.07679 0.07708 0.07713 0.07679 1.0130507523540014e+06 0.07702 1677890280000 1677890340000 6535}
{{XA} IOT-USD 0.22339 0.22339 0.22339 0.22339 3500 0.2234 1677890280000 1677890340000 1750}
{{XA} LPT-USD 6.43 6.46 6.46 6.43 236.727 6.4415 1677890280000 1677890340000 59}
{{XA} ADA-USD 0.3431 0.344 0.3441 0.343 52770.14474284 0.344 1677890280000 1677890340000 1034}
{{XA} ZRX-USD 0.251774 0.252 0.25244 0.251774 16089.65496736 0.252 1677890280000 1677890340000 1237}
{{XA} FIL-USD 6.279 6.302 6.307 6.279 1543.04794634 6.2994 1677890280000 1677890340000 31}
{{XA} USDC-USD 1.00012 0.9999 1.00012 0.9999 646.896238 1.0001 1677890280000 1677890340000 215}
{{XA} ICP-USD 5.584 5.603 5.61 5.584 2734.99037921 5.5961 1677890280000 1677890340000 62}
{{XA} CRO-USD 0.0736 0.0738 0.0738 0.0736 6563.6 0.0736 1677890280000 1677890340000 2187}
{{XA} XRD-USD 0.042501 0.042501 0.042501 0.042501 59.7006821 0.0425 1677890280000 1677890340000 29}
{{XA} ELA-USD 1.17 1.17 1.17 1.17 5.24 1.17 1677890280000 1677890340000 2}
{"file":"........../go/pkg/mod/github.com/polygon-io/client-go@v1.10.0/websocket/polygon.go:447","func":"github.com/polygon-io/client-go/websocket.(*Client).handleData","level":"error","message":"failed to unmarshal message: json: cannot unmarshal number 2.7820147e+07 into Go struct field CurrencyAgg.z of type int32","time":"2023-03-04T01:39:02+01:00"}
{{XA} QNT-USD 125.2 125.29 125.3 125.17 19.988 125.2578 1677890280000 1677890340000 0}
{{XA} VET-USD 0.025767 0.025767 0.025767 0.025767 238.5512706 0.02577 1677890280000 1677890340000 119}
{{XA} DUSK-USD 0.19851 0.19851 0.19851 0.19851 104.46555802 0.1985 1677890280000 1677890340000 26}
{{XA} FET-USD 0.4369 0.4386 0.439 0.4369 31142.7 0.4382 1677890280000 1677890340000 527}
{{XA} FLOW-USD 1.085 1.087 1.088 1.084 6756.99706997 1.0861 1677890280000 1677890340000 337}
{{XA} XRP-USD 0.37751 0.37828 0.37828 0.37751 6600 0.378 1677890280000 1677890340000 169}
{{XA} SPELL-USD 0.0007636 0.0007663 0.0007667 0.000763 3.4156544277007403e+06 0.0007657 1677890280000 1677890340000 126505}
{{XA} IMX-USD 1.0349 1.0373 1.0375 1.0349 1642.59 1.0369 1677890280000 1677890340000 234}
{{XA} BTC-GBP 18559 18567.9 18567.9 18555.3 0.04929 18559.341 1677890280000 1677890340000 0}
{{XA} NEAR-USD 2.111 2.114 2.114 2.1107 24.91028917 2.1119 1677890280000 1677890340000 4}
{{XA} MASK-USD 3.46 3.46 3.46 3.46 130 3.46 1677890280000 1677890340000 130}
{{XA} KAVA-USD 0.8003 0.802 0.802 0.8003 6.43 0.8011 1677890280000 1677890340000 1}
{{XA} REP-USD 8.5633 8.4497 8.5633 8.4497 1.18922492 8.5227 1677890280000 1677890340000 0}
{{XA} BOND-USD 4.47 4.47 4.47 4.47 17.832 4.47 1677890280000 1677890340000 4}
{{XA} ROSE-USD 0.05994 0.06019 0.06019 0.05994 94481.99224 0.06016 1677890280000 1677890340000 5905}
{{XA} LTC-EUR 85.07 85.28 85.28 85.07 15.70944633 85.2247 1677890280000 1677890340000 3}
{{XA} FX-USD 0.1904 0.1904 0.1904 0.1904 330.3 0.1904 1677890280000 1677890340000 110}
{{XA} YFI-USD 10686.77 10701.3 10711.27 10675.98 0.475102 10697.1941 1677890280000 1677890340000 0}
{{XA} IOTX-USD 0.03047 0.03047 0.03047 0.03047 3153 0.03047 1677890280000 1677890340000 3153}
{{XA} SOL-USD 21.41 21.46 21.47 21.4 4534.002 21.4489 1677890280000 1677890340000 82}
{{XA} NEO-USD 12.007 12.007 12.007 12.007 12.2 12.007 1677890280000 1677890340000 6}
{{XA} ZEN-USD 11.05 11.08 11.08 11.05 20.583 11.0559 1677890280000 1677890340000 0}
{{XA} ATOM-USD 12.021 12.057 12.057 12.02 108.96635078 12.0401 1677890280000 1677890340000 7}
{{XA} SKL-USD 0.044 0.0441 0.0441 0.044 17331 0.0441 1677890280000 1677890340000 3466}
{{XA} USDT-USD 1.00006 1.00006 1.0001 1.00005 17150.1859 1.0001 1677890280000 1677890340000 64}
{{XA} XMR-USD 145.33 145.33 145.33 145.33 0.04287532 145.33 1677890280000 1677890340000 0}
{{XA} BAL-USD 6.53 6.53 6.53 6.53 20 6.53 1677890280000 1677890340000 20}
{{XA} DOT-USD 6.021 6.038 6.0405 6.021 307.37283984 6.0312 1677890280000 1677890340000 15}
{{XA} ARPA-USD 0.0388 0.03893 0.03893 0.0388 39636.09554415 0.03893 1677890280000 1677890340000 9909}
{{XA} REQ-USD 0.1028 0.1028 0.1028 0.1028 32 0.1028 1677890280000 1677890340000 32}
{{XA} STORJ-USD 0.3926 0.3928 0.3928 0.3926 4490.2 0.3927 1677890280000 1677890340000 1122}
{{XA} BNT-USD 0.4548 0.4559 0.4559 0.4548 25.953396 0.4555 1677890280000 1677890340000 3}
{{XA} ALGO-USD 0.2331 0.2337 0.2338 0.2331 40076.3364 0.2337 1677890280000 1677890340000 1113}
{{XA} BTRST-USD 0.942 0.942 0.942 0.942 14.5 0.942 1677890280000 1677890340000 14}
{{XA} BTC-USD 22344.77 22369.73 22376.27 22344.77 4.6140239 22365.0054 1677890280000 1677890340000 0}
{{XA} XVG-USD 0.0030754 0.0030754 0.0030754 0.0030754 897.47773018 0.003075 1677890280000 1677890340000 448}
{{XA} HBAR-USD 0.06494 0.06507 0.06507 0.06493 155023.4 0.06496 1677890280000 1677890340000 15502}
{{XA} RLY-USD 0.0237 0.0236 0.0237 0.0236 36592 0.02369 1677890280000 1677890340000 3659}
{{XA} BTC-AUD 33029.4 33037 33037 33029.4 0.07604829 33036.7587 1677890280000 1677890340000 0}
{{XA} JST-USD 0.027655 0.027618 0.027655 0.027618 309.74222282 0.02764 1677890280000 1677890340000 77}
{{XA} COTI-USD 0.0822 0.0822 0.0822 0.0822 12.1 0.0822 1677890280000 1677890340000 12}
{{XA} UMA-USD 2.048 2.051 2.053 2.048 1911.095 2.0512 1677890280000 1677890340000 119}
{{XA} PERP-USD 0.9969 0.9983 0.9983 0.9969 188.741 0.9969 1677890280000 1677890340000 94}
{{XA} RNDR-USD 1.3592 1.3657 1.3683 1.3592 1246.75465584 1.3664 1677890280000 1677890340000 28}
{{XA} OXT-USD 0.0945 0.0945 0.0945 0.0945 5232 0.0945 1677890280000 1677890340000 1308}
{{XA} XLM-USD 0.085415 0.085557 0.085619 0.085415 112242.01507513 0.08552 1677890280000 1677890340000 1537}
{{XA} BCH-USD 126.63 126.8 126.94 126.62 86.54428914 126.7572 1677890280000 1677890340000 1}
{{XA} BAT-USD 0.27123 0.27134 0.27134 0.27123 1393.01774 0.2713 1677890280000 1677890340000 464}
{{XA} FORTH-USD 4.04 4.04 4.04 4.04 0.084 4.04 1677890280000 1677890340000 0}
{{XA} GALA-USD 0.03767 0.03778 0.03781 0.03767 355378.59660104 0.03775 1677890280000 1677890340000 10769}
{{XA} GRT-USD 0.1473 0.1478 0.148 0.1473 18313.71926123 0.1477 1677890280000 1677890340000 963}
{{XA} COMP-USD 47.83 48.03 48.07 47.83 74.896 47.9708 1677890280000 1677890340000 1}
{{XA} STX-USD 0.8316 0.8335 0.8335 0.8316 1010.26293 0.8335 1677890280000 1677890340000 168}
{{XA} GNO-USD 103.3 103.15 103.3 103.15 0.25528036 103.1847 1677890280000 1677890340000 0}
{{XA} IQX-USD 0.0063614 0.0065924 0.0065924 0.0063614 1997.2315143 0.006453 1677890280000 1677890340000 499}
{{XA} DASH-USD 69.5 69.63 69.63 69.5 1.235 69.5168 1677890280000 1677890340000 0}
{{XA} MATIC-USD 1.17 1.1738 1.1741 1.17 15687.75758146 1.1728 1677890280000 1677890340000 249}
{{XA} DAI-USD 0.99972 0.9999 0.9999 0.99972 2589.88118422 0.9997 1677890280000 1677890340000 369}
{{XA} SUSHI-USD 1.2439 1.2474 1.2488 1.2439 2198.87319592 1.2471 1677890280000 1677890340000 95}
{{XA} AXS-USD 9.18 9.22 9.23 9.18 1011.55395992 9.213 1677890280000 1677890340000 56}
{{XA} OCEAN-USD 0.3922 0.3922 0.3928 0.3922 2407.3905 0.3922 1677890280000 1677890340000 601}
{{XA} UNI-USD 6.276 6.288 6.29 6.276 85.701382 6.2785 1677890280000 1677890340000 5}
{{XA} ACH-USD 0.0328 0.032919 0.032927 0.032755 253442.9 0.03288 1677890280000 1677890340000 11019}
{{XA} APE-USD 4.821 4.827 4.827 4.8202 1886.89530426 4.8258 1677890280000 1677890340000 235}
{{XA} 1INCH-USD 0.532 0.532 0.532 0.532 900 0.532 1677890280000 1677890340000 900}
{{XA} OMG-USD 1.583 1.5886 1.5899 1.583 3143.3 1.587 1677890280000 1677890340000 224}
{{XA} BAND-USD 1.827 1.832 1.833 1.827 350.78 1.8303 1677890280000 1677890340000 35}
{{XA} CGLD-USD 0.693 0.695 0.695 0.692 1105.22 0.6935 1677890280000 1677890340000 276}
{{XA} AVAX-USD 16.72 16.768 16.78 16.72 676.10227162 16.7651 1677890280000 1677890340000 22}
{{XA} INJ-USD 3.682 3.682 3.682 3.682 7.98 3.682 1677890280000 1677890340000 7}
{{XA} CRV-USD 0.9395 0.9406 0.9408 0.9395 1492.48 0.9404 1677890280000 1677890340000 298}
{{XA} LTC-USD 90.48 90.7 90.77 90.45 161.05330388 90.5867 1677890280000 1677890340000 2}
{{XA} CHZ-USD 0.1271 0.1275 0.1275 0.1271 13423.81286231 0.1274 1677890280000 1677890340000 1342}
{{XA} FTM-USD 0.42894 0.42945 0.42975 0.42894 63.59629966 0.4295 1677890280000 1677890340000 10}
{{XA} REN-USD 0.1242 0.1243 0.1243 0.1242 33212.375 0.1243 1677890280000 1677890340000 8303}
{{XA} VGX-USD 0.3339 0.3342 0.3342 0.3339 1307 0.334 1677890280000 1677890340000 217}
{{XA} CTSI-USD 0.152 0.1521 0.1522 0.1518 13919.20382026 0.1521 1677890280000 1677890340000 2319}
{{XA} CLV-USD 0.0738 0.0738 0.0738 0.0738 700 0.0738 1677890280000 1677890340000 700}
{{XA} AMP-USD 0.00513 0.00513 0.00514 0.00513 57816 0.00513 1677890280000 1677890340000 6424}
{{XA} MOB-USD 1.6662 1.6662 1.6662 1.6662 0.76840524 1.6662 1677890280000 1677890340000 0}
{{XA} ZEC-USD 39.74 39.86 39.86 39.74 140.5179998 39.8431 1677890280000 1677890340000 8}
{{XA} XDC-USD 0.029619 0.029619 0.029619 0.029619 4000 0.02962 1677890280000 1677890340000 2000}
{{XA} EOS-USD 1.3245 1.3299 1.3318 1.3245 55042.58154933 1.3296 1677890280000 1677890340000 423}
{{XA} SNX-USD 2.902 2.915 2.917 2.902 5552.31003265 2.9137 1677890280000 1677890340000 231}
{{XA} ETC-USD 20.33 20.4 20.4 20.33 106.38476685 20.3652 1677890280000 1677890340000 5}
{{XA} NKN-USD 0.1101 0.1104 0.1104 0.1101 28856.8 0.1103 1677890280000 1677890340000 2623}
{{XA} MKR-USD 915.81 915.34 917.65 915.34 8.028597 916.6859 1677890280000 1677890340000 0}
{{XA} LINK-USD 6.972 6.989 6.989 6.972 414.74482108 6.9793 1677890280000 1677890340000 34}
{{XA} KSM-USD 34.192 34.192 34.192 34.192 0.0484622 34.192 1677890280000 1677890340000 0}
{{XA} XTZ-USD 1.144 1.145 1.1466 1.144 1172.79 1.1456 1677890280000 1677890340000 167}
{{XA} XRP-BTC 1.69e-05 1.69e-05 1.69e-05 1.69e-05 50000 1.69e-05 1677890280000 1677890340000 3846}
{{XA} ANKR-USD 0.03553 0.03563 0.03563 0.03553 220251 0.03555 1677890280000 1677890340000 18354}`

Hope this will help

**Comment by justinpolygon** [comment] 2023-03-09 18:46
Thanks for posting this. Just a heads up, I am looking into it but don't have any fixes yet.

**Comment by justinpolygon** [comment] 2023-04-26 04:33
Hey, I'm going to close this since I still cannot reproduce it. If you have any other details please let me know and we'll dig into it.

**Closed by justinpolygon** 2023-04-26 04:33 UTC
Labels: bug
