### ISSUE TITLE
How to keep the connection alive (it keeps dropping regardless of volume)

### ISSUE THREAD

**Issue by nickmachairas** [polygon-io/client-go#6] opened 2021-03-19 15:09 UTC
I followed your websocket example. Performance is great, however, the connection is frequently dropped during trading hours **and not because of my client not processing the messages fast enough**. What's worse is that the connection drops without an error and the process is just suspended. I tried to implement Gorilla's chat example sending pings and receiving pongs but it didn't work, in fact it appears that the pongs are not returned at all during trading hours.

Any advice on how I can keep the connection alive? Thanks!

**Comment by gcatlin** [comment] 2021-03-19 15:20
There's an [implementation by Alpaca](https://github.com/alpacahq/alpaca-trade-api-go/blob/master/polygon/stream.go) that might be worth a look -- though I haven't used it myself so I can't vouch for it. It looks like it reconnects whenever a `ReadMessage()` returns an error.

**Comment by gcatlin** [comment] 2021-03-19 15:44
FWIW, I'm using [wscat](https://github.com/websockets/wscat) and outputting to a file which my Go program is [tailing](https://github.com/hpcloud/tail). It's janky and probably adds a ton of latency, but it works reliably and the connection is stable, so I don't think the problem is on Polygon's side.

**Comment by nickmachairas** [comment] 2021-03-19 15:45
Which stream are you subscribed to?

**Comment by gtmk** [comment] 2021-03-19 16:02
FWIW, when I was using the Alpaca key to access Polygon data with my own version of Alpaca's client, I barely got connection drops, say once a week or so. I don't have that access anymore since Alpaca and Polygon split, but expecting the same connection quality.

**Comment by gcatlin** [comment] 2021-03-19 16:04
I've only used the stocks cluster so far, but I've subscribed to `A.*,AM.*,T,*,Q*` successfully -- though only very briefly due to the high volume and since I write it all to disk. I've also subscribed to the A, AM, T, and Q streams for ~25 stocks (so ~100 total subscriptions) simultaneously, all-day during market hours, on many different days, with no problems.

**Comment by nickmachairas** [comment] 2021-03-19 16:29
@gcatlin what you are describing confirms what I am seeing: there are likely server issues on high volume streams. Polygon keeps saying it is a client problem and that's why I moved to Golang which is more performant. I subscribe to ``A.*,AM.*`` and my Polygon dashboard shows an average of ~350 msgs/sec with minute spikes due to ``AM`` and there are no buffered messages while my CPU load is a cool 6%. I take all that as signs that my client is performing okay yet the connection keeps getting dropped regardless. I haven't tried ``wscat`` yet, I will, but I don't understand how it can perform better than Go, or how to use it to publish messages to a MQ. This was a learning opportunity for me hopefully one day leading to processing ``T.*,Q.*``. It has been frustrating to see my systems underutilized with connection drops on much lower volumes than ``T.*``'s average 2,000 msgs/sec. There's plenty I might be doing wrong, of course, and communication with Polygon's support all these days would have been great.

@gtmk thank you for the insight. Connection reliability is extremely important, if I find that Alpaca's API is more reliable I will certainly opt to build my systems around that instead.

**Comment by gcatlin** [comment] 2021-03-19 20:20
To clarify, I shut down the `T.*,Q.*` streams because I didn't want my disk to fill up. I just tried it again with `wscat` and had it print messages to stdout instead of redirecting to a file. I let it run for an hour or so with no problems. The dashboard  showed 6-7k msgs/sec.

What MQ are you using? You could, for example, use a tool like [Vector](https://vector.dev/), to transfer a file (e.g. from wscat output) to Kafka, AWS Kinesis, NATS, etc.

**Comment by nickmachairas** [comment] 2021-03-19 20:34
Thanks for taking the time to test this out, I appreciate it. I will test this too once trading activity resumes. But I am having such a hard time wrapping my head around it. How is it possible that simple Python and Golang script fail, the latter far more performant than the others, while wscat is stable? [Gorilla](https://github.com/gorilla/websocket) is a popular and battle-proven library, how can it be possible that only wscat get's along with Polygon's servers? Maybe it's a JS thing? I have no idea...

Ideally I want a setup-and-forget tech stack, meaning, everything on GCP with PubSub for the MQ. Have a reliable data stream and storage so that I focus on modeling only. I set everything up on GCP and it works amazingly well with low latency, minus the connection drops. On my local setup I am testing Kafka. I will eventually go with whatever is more reliable.

**Comment by mimap** [comment] 2021-06-07 19:04
There is an example of a polygon golang client [here](https://github.com/polygon-io/client-examples/blob/master/websockets/golang/main.go). The key takeaway, from the example, is to get the incoming polygon message off the wire right away and into your own channel. The amount of work you are doing in your reader loop is more telling to performance than the msgs/second. Hope that helps a bit.

**Comment by morningvera** [comment] 2022-04-22 15:28
Closing this issue. We're currently working on a client that automatically reconnects and it'll be part of the v1 release!

**Closed by morningvera** 2022-04-22 15:28 UTC
